server:
    port: ${PORT:9000}
spring:
  application:
      name: reactive-spring-server
  profiles:
      active: local

logging:
  level:
     ROOT: INFO
     com.alexkbit.intro: DEBUG
     org.springframework: INFO

spring:
  data.mongodb:
    uri: mongodb://localhost:27017/reactive-spring

---
spring:
  profiles: local

---
spring:
  profiles: test
